apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-service-sa
  namespace: ai-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: worker-serving-role
  namespace: model-serving
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-serving-rolebinding
  namespace: model-serving
subjects:
  - kind: ServiceAccount
    name: worker-service-sa
    namespace: ai-deploy
roleRef:
  kind: Role
  name: worker-serving-role
  apiGroup: rbac.authorization.k8s.io
